; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32s3-devkitc-1]
platform = espressif32
;board = esp32-s3-devkitc-1
board = esp32s3usbotg
framework = arduino
monitor_speed = 115200


build_flags = 
    -std=gnu++17        ; ← Añadir esta línea
;    -std=c++17          ; ← O esta (sin extensiones GNU)
    -O2
    -DDEBUG_SPI_PROTOCOL    ; Opcional: activar debug SPI

board_build.arduino.partitions = app3M_fat9M_16MB.csv 
    
; Flash and PSRAM IO mode
board_build.arduino.memory_type = qio_opi ; or opi_opi, depending on your module
    
;Assert PSRAM presence
board_build.arduino.psram = enabled    
; Assert flash size
board_upload.flash_size = 16MB

monitor_filters =
    esp32_exception_decoder

lib_deps = 
    https://github.com/pololu/vl53l0x-arduino.git#1.3.0  ; Biblioteca VL53L0X de Pololu
    adafruit/Adafruit BusIO@^1.14.1


build_type = debug